Repository mash-up-kr/SeeYouAgain_iOS, pull requests merged in 2023-11, with the labels that each got.

#224 수정: 1.4.0 업데이트 사항 반영
  Projects/App/Info.plist
  Projects/Core/Services/Category/CategoryAPI.swift
  Projects/Core/Services/HotKeyword/HotKeywordAPI.swift
  Projects/Core/Services/Log/LogAPI.swift
  Projects/Core/Services/MyPage/MyPageAPI.swift
  Projects/Core/Services/NewsCard/NewsCardAPI.swift
  Projects/Core/Services/Setting/SettingAPI.swift
  Projects/DesignSystem/Resources/Images/Images.xcassets/CategoryStatistics/icon_category_culture.imageset/Contents.json
  Projects/DesignSystem/Resources/Images/Images.xcassets/CategoryStatistics/icon_category_culture.imageset/icon_category_culture.svg
  Projects/DesignSystem/Resources/Images/Images.xcassets/CategoryStatistics/icon_category_economics.imageset/Contents.json
  Projects/DesignSystem/Resources/Images/Images.xcassets/CategoryStatistics/icon_category_economics.imageset/icon_category_economics.svg
  Projects/DesignSystem/Resources/Images/Images.xcassets/CategoryStatistics/icon_category_politics.imageset/Contents.json
  Projects/DesignSystem/Resources/Images/Images.xcassets/CategoryStatistics/icon_category_politics.imageset/icon_category_politics.svg
  Projects/DesignSystem/Resources/Images/Images.xcassets/CategoryStatistics/icon_category_science.imageset/Contents.json
  Projects/DesignSystem/Resources/Images/Images.xcassets/CategoryStatistics/icon_category_science.imageset/icon_category_science.svg
  Projects/DesignSystem/Resources/Images/Images.xcassets/CategoryStatistics/icon_category_society.imageset/Contents.json
  Projects/DesignSystem/Resources/Images/Images.xcassets/CategoryStatistics/icon_category_society.imageset/icon_category_society.svg
  Projects/DesignSystem/Resources/Images/Images.xcassets/CategoryStatistics/icon_category_world.imageset/Contents.json
  Projects/DesignSystem/Resources/Images/Images.xcassets/CategoryStatistics/icon_category_world.imageset/icon_category_world.svg
  Projects/DesignSystem/Resources/Images/Images.xcassets/Statistics/Contents.json
  Projects/DesignSystem/Resources/Images/Images.xcassets/Statistics/statistics_culture.imageset/Contents.json
  Projects/DesignSystem/Resources/Images/Images.xcassets/Statistics/statistics_culture.imageset/statistics_culture@1x.png
  Projects/DesignSystem/Resources/Images/Images.xcassets/Statistics/statistics_culture.imageset/statistics_culture@2x.png
  Projects/DesignSystem/Resources/Images/Images.xcassets/Statistics/statistics_culture.imageset/statistics_culture@3x.png
  Projects/DesignSystem/Resources/Images/Images.xcassets/Statistics/statistics_economics.imageset/Contents.json
  Projects/DesignSystem/Resources/Images/Images.xcassets/Statistics/statistics_economics.imageset/statistics_economics@1x.png
  Projects/DesignSystem/Resources/Images/Images.xcassets/Statistics/statistics_economics.imageset/statistics_economics@2x.png
  Projects/DesignSystem/Resources/Images/Images.xcassets/Statistics/statistics_economics.imageset/statistics_economics@3x.png
  Projects/DesignSystem/Resources/Images/Images.xcassets/Statistics/statistics_politics.imageset/Contents.json
  Projects/DesignSystem/Resources/Images/Images.xcassets/Statistics/statistics_politics.imageset/statistics_politics@1x.png
  Projects/DesignSystem/Resources/Images/Images.xcassets/Statistics/statistics_politics.imageset/statistics_politics@2x.png
  Projects/DesignSystem/Resources/Images/Images.xcassets/Statistics/statistics_politics.imageset/statistics_politics@3x.png
  Projects/DesignSystem/Resources/Images/Images.xcassets/Statistics/statistics_science.imageset/Contents.json
  Projects/DesignSystem/Resources/Images/Images.xcassets/Statistics/statistics_science.imageset/statistics_science@1x.png
  Projects/DesignSystem/Resources/Images/Images.xcassets/Statistics/statistics_science.imageset/statistics_science@2x.png
  Projects/DesignSystem/Resources/Images/Images.xcassets/Statistics/statistics_science.imageset/statistics_science@3x.png
  Projects/DesignSystem/Resources/Images/Images.xcassets/Statistics/statistics_society.imageset/Contents.json
  Projects/DesignSystem/Resources/Images/Images.xcassets/Statistics/statistics_society.imageset/statistics_society@1x.png
  Projects/DesignSystem/Resources/Images/Images.xcassets/Statistics/statistics_society.imageset/statistics_society@2x.png
  Projects/DesignSystem/Resources/Images/Images.xcassets/Statistics/statistics_society.imageset/statistics_society@3x.png
  Projects/DesignSystem/Resources/Images/Images.xcassets/Statistics/statistics_world.imageset/Contents.json
  Projects/DesignSystem/Resources/Images/Images.xcassets/Statistics/statistics_world.imageset/statistics_world@1x.png
  Projects/DesignSystem/Resources/Images/Images.xcassets/Statistics/statistics_world.imageset/statistics_world@2x.png
  Projects/DesignSystem/Resources/Images/Images.xcassets/Statistics/statistics_world.imageset/statistics_world@3x.png
  Projects/Features/Coordinator/ShortStorageCoordinator/ShortStorageCoordinatorCore.swift
  Projects/Features/Scene/LongStorageScene/LongStorageNewsList/LongShortsItem/LongShortsItemCore.swift
  Projects/Features/Scene/LongStorageScene/LongStorageNewsList/LongStorageNewsListCore.swift
  Projects/Features/Scene/LongStorageScene/LongStorageNewsList/LongStorageNewsListView.swift
  Projects/Features/Scene/MyPageScene/MyPage/Statistics/StatisticsView.swift
  Projects/Features/Scene/ShortStorageScene/ShortStorageNewsList/ShortStorageNewsListCore.swift
  Projects/Features/Scene/ShortStorageScene/ShortStorageNewsList/ShortStorageNewsListView.swift
  Projects/Features/Scene/ShortStorageScene/ShortStorageNewsList/TodayShortsItem/TodayShortsCardCore.swift
  Projects/Features/Scene/ShortStorageScene/ShortStorageNewsList/TodayShortsItem/TodayShortsItemCore.swift
  Projects/Features/Scene/TabBarScene/TabBar/TabBarCore.swift
  Projects/Features/Scene/WebScene/Web/WebCore.swift
Labels: 수정, ⭐️⭐️ㅤ

#225 :bookmark: v1.4.0-202311132118
  Projects/App/Info.plist
  Projects/App/xcconfigs/SeeYouAgain.shared.xcconfig
Labels: 인프라

#227 기능: 햅틱 추가 및 관심 키워드 변경 성공 시 토스트 메시지 추가
  Projects/App/xcconfigs/SeeYouAgain.shared.xcconfig
  Projects/Features/Scene/LongStorageScene/LongStorageNewsList/LongStorageNewsListView.swift
  Projects/Features/Scene/MyPageScene/MyPage/Achievements/MyAchievementsView.swift
  Projects/Features/Scene/MyPageScene/MyPage/MyPageView.swift
  Projects/Features/Scene/MyPageScene/MyPage/Statistics/WeeklyStatistics/WeeklyStatisticsCore.swift
  Projects/Features/Scene/MyPageScene/MyPage/Statistics/WeeklyStatistics/WeeklyStatisticsDescriptionView.swift
  Projects/Features/Scene/NewsCardScene/NewsList/NewsListView.swift
  Projects/Features/Scene/ShortStorageScene/ShortStorageNewsList/ShortStorageNewsListView.swift
  Projects/Features/Scene/TabBarScene/BottomSheet/CategoryBottomSheetContent.swift
  Projects/Features/Scene/TabBarScene/BottomSheet/CategoryBottomSheetCore.swift
  Projects/Features/Scene/TabBarScene/TabBar/ShortsTabBarView.swift
  Projects/Features/Scene/TabBarScene/TabBar/TabBarView.swift
  Projects/Features/Scene/WebScene/Web/WebView.swift
Labels: 기능, ⭐️⭐️ㅤ

#228 :bookmark: v1.5.0-202311271912
  Projects/App/Info.plist
Labels: 인프라
