Repository mash-up-kr/SeeYouAgain_iOS, pull requests merged in 2023-08, with the labels that each got.

#197 기능: 로그 API 및 Service 구현
  Projects/App/Sources/AppView/AppView.swift
  Projects/Core/Services/Log/LogAPI.swift
  Projects/Core/Services/Log/LogService.swift
  Projects/Features/Coordinator/AppCoordinator/AppCoordinatorCore.swift
  Projects/Features/Coordinator/AppCoordinator/AppScreenCore.swift
  Projects/Features/Scene/SplashScene/Splash/SplashCore.swift
Labels: ⭐️ㅤ

#199 기능: 업적 API 연결 및 공유 기능 구현
  Projects/Core/Common/AchievementBadge/AchievementType.swift
  Projects/Core/Models/MyPage/Achievement.swift
  Projects/Core/Models/MyPage/AchievementType.swift
  Projects/Core/Models/Network/MyPage/ResponseDTO/AchievementResponseDTO.swift
  Projects/Core/Services/MyPage/MyPageAPI.swift
  Projects/Core/Services/MyPage/MyPageService.swift
  Projects/DesignSystem/Resources/Icons/Icons.xcassets/Icons/My/icon_selct_large.imageset/Contents.json
  Projects/DesignSystem/Resources/Icons/Icons.xcassets/Icons/My/icon_selct_large.imageset/icon_selct_large@1x.png
  Projects/DesignSystem/Resources/Icons/Icons.xcassets/Icons/My/icon_selct_large.imageset/icon_selct_large@2x.png
  Projects/DesignSystem/Resources/Icons/Icons.xcassets/Icons/My/icon_selct_large.imageset/icon_selct_large@3x.png
  Projects/DesignSystem/Resources/Images/Images.xcassets/AchievementShare/Contents.json
  Projects/DesignSystem/Resources/Images/Images.xcassets/AchievementShare/bg_record.imageset/Contents.json
  Projects/DesignSystem/Resources/Images/Images.xcassets/AchievementShare/bg_record.imageset/bg_record@1X.png
  Projects/DesignSystem/Resources/Images/Images.xcassets/AchievementShare/bg_record.imageset/bg_record@2x.png
  Projects/DesignSystem/Resources/Images/Images.xcassets/AchievementShare/bg_record.imageset/bg_record@3x.png
  Projects/DesignSystem/Resources/Images/Images.xcassets/AchievementShare/img_share.imageset/Contents.json
  Projects/DesignSystem/Resources/Images/Images.xcassets/AchievementShare/img_share.imageset/작심삼일@1x.png
  Projects/DesignSystem/Resources/Images/Images.xcassets/AchievementShare/img_share.imageset/작심삼일@2x.png
  Projects/DesignSystem/Resources/Images/Images.xcassets/AchievementShare/img_share.imageset/작심삼일@3x.png
  Projects/Features/Coordinator/MyPageCoordinator/MyPageCoordinatorCore.swift
  Projects/Features/Scene/MyPageScene/MyPage/AchievementShare/AchievementShareView.swift
  Projects/Features/Scene/MyPageScene/MyPage/Achievements/MyAchievementsCore.swift
  Projects/Features/Scene/MyPageScene/MyPage/Achievements/MyAchievementsView.swift
  Projects/Features/Scene/TabBarScene/BottomSheet/AchievementBottomSheet.swift
  Projects/Features/Scene/TabBarScene/BottomSheet/CategoryBottomSheetContent.swift
  Projects/Features/Scene/TabBarScene/BottomSheet/CategoryBottomSheetCore.swift
  Projects/Features/Scene/TabBarScene/TabBar/TabBarCore.swift
  Projects/Features/Scene/TabBarScene/TabBar/TabBarView.swift
  Tuist/ResourceSynthesizers/Assets.stencil
  Tuist/ResourceSynthesizers/Fonts.stencil
Labels: 기능, ⭐️ㅤ

#205 main api uri 변경 적용
  Projects/Core/Models/Network/NewsCard/RequestDTO/NewsCardsRequestDTO.swift
  Projects/Core/Models/Network/NewsCard/ResponseDTO/AllNewsCardReponseDTO.swift
  Projects/Core/Services/NewsCard/NewsCardAPI.swift
  Projects/Core/Services/NewsCard/NewsCardService.swift
Labels: ⭐️⭐️⭐️ㅤ

#203 기능: 읽음 처리 방식 및 기획, 디자인 변경사항 수정
  Projects/Core/Models/MyPage/KeywordNews.swift
  Projects/Core/Models/MyPage/KeywordNewsCard.swift
  Projects/Core/Models/MyPage/TodayShorts.swift
  Projects/Core/Models/MyPage/User.swift
  Projects/Core/Models/Network/MyPage/MemberInfoResponseDTO.swift
  Projects/Core/Models/Network/MyPage/RequestDTO/KeywordNewsCardRequestDTO.swift
  Projects/Core/Models/Network/MyPage/RequestDTO/TodayShortsRequestDTO.swift
  Projects/Core/Models/Network/MyPage/ResponseDTO/KeywordNewsCardResponseDTO.swift
  Projects/Core/Models/Network/MyPage/ResponseDTO/TodayShortsResponseDTO.swift
  Projects/Core/Models/Network/News/RequestDTO/SavedNewsRequestDTO.swift
  Projects/Core/Services/MyPage/MyPageAPI.swift
  Projects/Core/Services/MyPage/MyPageService.swift
  Projects/Core/Services/NewsCard/NewsCardAPI.swift
  Projects/Core/Services/NewsCard/NewsCardService.swift
  Projects/Features/Scene/LongStorageScene/LongStorageNewsList/LongShortsItem/LongShortsCardView.swift
  Projects/Features/Scene/LongStorageScene/LongStorageNewsList/LongStorageNewsListCore.swift
  Projects/Features/Scene/LongStorageScene/LongStorageNewsList/LongStorageNewsListView.swift
  Projects/Features/Scene/MyPageScene/MyPage/MyInfo/MyInfoCore.swift
  Projects/Features/Scene/MyPageScene/MyPage/MyInfo/MyInfoShortsCore.swift
  Projects/Features/Scene/MyPageScene/MyPage/MyInfo/MyInfoShortsView.swift
  Projects/Features/Scene/MyPageScene/MyPage/MyInfo/MyInfoView.swift
  Projects/Features/Scene/NewsCardScene/NewsList/NewsCard/NewsCardView.swift
  Projects/Features/Scene/NewsCardScene/NewsList/NewsListView.swift
  Projects/Features/Scene/ShortStorageScene/ShortStorageNewsList/ShortStorageNewsListCore.swift
  Projects/Features/Scene/ShortStorageScene/ShortStorageNewsList/ShortStorageNewsListView.swift
  Projects/Features/Scene/ShortStorageScene/ShortStorageNewsList/TodayShortsItem/TodayShortsCardView.swift
  Projects/Features/Scene/WebScene/Web/WebCore.swift
  Projects/Features/Scene/WebScene/Web/WebView.swift
Labels: 기능, 디자인, ⭐️⭐️⭐️ㅤ

#212 디자인: 카테고리 설정 화면 디자인 에셋 변경
  Projects/DesignSystem/Resources/Icons/Icons.xcassets/Icons/Category/culture.imageset/Contents.json
  Projects/DesignSystem/Resources/Icons/Icons.xcassets/Icons/Category/culture.imageset/culture.svg
  Projects/DesignSystem/Resources/Icons/Icons.xcassets/Icons/Category/culture.imageset/culture@1x.png
  Projects/DesignSystem/Resources/Icons/Icons.xcassets/Icons/Category/culture.imageset/culture@2x.png
  Projects/DesignSystem/Resources/Icons/Icons.xcassets/Icons/Category/culture.imageset/culture@3x.png
  Projects/DesignSystem/Resources/Icons/Icons.xcassets/Icons/Category/economics.imageset/Contents.json
  Projects/DesignSystem/Resources/Icons/Icons.xcassets/Icons/Category/economics.imageset/economic@1x.png
  Projects/DesignSystem/Resources/Icons/Icons.xcassets/Icons/Category/economics.imageset/economic@2x.png
  Projects/DesignSystem/Resources/Icons/Icons.xcassets/Icons/Category/economics.imageset/economic@3x.png
  Projects/DesignSystem/Resources/Icons/Icons.xcassets/Icons/Category/economics.imageset/economics.svg
  Projects/DesignSystem/Resources/Icons/Icons.xcassets/Icons/Category/politics.imageset/Contents.json
  Projects/DesignSystem/Resources/Icons/Icons.xcassets/Icons/Category/politics.imageset/politics.svg
  Projects/DesignSystem/Resources/Icons/Icons.xcassets/Icons/Category/politics.imageset/politics@1x.png
  Projects/DesignSystem/Resources/Icons/Icons.xcassets/Icons/Category/politics.imageset/politics@2x.png
  Projects/DesignSystem/Resources/Icons/Icons.xcassets/Icons/Category/politics.imageset/politics@3x.png
  Projects/DesignSystem/Resources/Icons/Icons.xcassets/Icons/Category/science.imageset/Contents.json
  Projects/DesignSystem/Resources/Icons/Icons.xcassets/Icons/Category/science.imageset/science.svg
  Projects/DesignSystem/Resources/Icons/Icons.xcassets/Icons/Category/science.imageset/science@1x.png
  Projects/DesignSystem/Resources/Icons/Icons.xcassets/Icons/Category/science.imageset/science@2x.png
  Projects/DesignSystem/Resources/Icons/Icons.xcassets/Icons/Category/science.imageset/science@3x.png
  Projects/DesignSystem/Resources/Icons/Icons.xcassets/Icons/Category/selectedCulture.imageset/Contents.json
  Projects/DesignSystem/Resources/Icons/Icons.xcassets/Icons/Category/selectedCulture.imageset/selectedCulture.svg
  Projects/DesignSystem/Resources/Icons/Icons.xcassets/Icons/Category/selectedCulture.imageset/selectedCulture@1x.png
  Projects/DesignSystem/Resources/Icons/Icons.xcassets/Icons/Category/selectedCulture.imageset/selectedCulture@2x.png
  Projects/DesignSystem/Resources/Icons/Icons.xcassets/Icons/Category/selectedCulture.imageset/selectedCulture@3x.png
  Projects/DesignSystem/Resources/Icons/Icons.xcassets/Icons/Category/selectedEconomics.imageset/Contents.json
  Projects/DesignSystem/Resources/Icons/Icons.xcassets/Icons/Category/selectedEconomics.imageset/selectedEconomics.svg
  Projects/DesignSystem/Resources/Icons/Icons.xcassets/Icons/Category/selectedEconomics.imageset/selectedEconomics@1x.png
  Projects/DesignSystem/Resources/Icons/Icons.xcassets/Icons/Category/selectedEconomics.imageset/selectedEconomics@2x.png
  Projects/DesignSystem/Resources/Icons/Icons.xcassets/Icons/Category/selectedEconomics.imageset/selectedEconomics@3x.png
  Projects/DesignSystem/Resources/Icons/Icons.xcassets/Icons/Category/selectedPolitics.imageset/Contents.json
  Projects/DesignSystem/Resources/Icons/Icons.xcassets/Icons/Category/selectedPolitics.imageset/selectedPolitics.svg
  Projects/DesignSystem/Resources/Icons/Icons.xcassets/Icons/Category/selectedPolitics.imageset/selectedPolitics@1x.png
  Projects/DesignSystem/Resources/Icons/Icons.xcassets/Icons/Category/selectedPolitics.imageset/selectedPolitics@2x.png
  Projects/DesignSystem/Resources/Icons/Icons.xcassets/Icons/Category/selectedPolitics.imageset/selectedPolitics@3x.png
  Projects/DesignSystem/Resources/Icons/Icons.xcassets/Icons/Category/selectedScience.imageset/Contents.json
  Projects/DesignSystem/Resources/Icons/Icons.xcassets/Icons/Category/selectedScience.imageset/selectedScience.svg
  Projects/DesignSystem/Resources/Icons/Icons.xcassets/Icons/Category/selectedScience.imageset/selectedScience@1x.png
  Projects/DesignSystem/Resources/Icons/Icons.xcassets/Icons/Category/selectedScience.imageset/selectedScience@2x.png
  Projects/DesignSystem/Resources/Icons/Icons.xcassets/Icons/Category/selectedScience.imageset/selectedScience@3x.png
  Projects/DesignSystem/Resources/Icons/Icons.xcassets/Icons/Category/selectedSociety.imageset/Contents.json
  Projects/DesignSystem/Resources/Icons/Icons.xcassets/Icons/Category/selectedSociety.imageset/selectedSociety.svg
  Projects/DesignSystem/Resources/Icons/Icons.xcassets/Icons/Category/selectedSociety.imageset/selectedSociety@1x.png
  Projects/DesignSystem/Resources/Icons/Icons.xcassets/Icons/Category/selectedSociety.imageset/selectedSociety@2x.png
  Projects/DesignSystem/Resources/Icons/Icons.xcassets/Icons/Category/selectedSociety.imageset/selectedSociety@3x.png
  Projects/DesignSystem/Resources/Icons/Icons.xcassets/Icons/Category/selectedWorld.imageset/Contents.json
  Projects/DesignSystem/Resources/Icons/Icons.xcassets/Icons/Category/selectedWorld.imageset/selectedWorld.svg
  Projects/DesignSystem/Resources/Icons/Icons.xcassets/Icons/Category/selectedWorld.imageset/selectedWorld@1x.png
  Projects/DesignSystem/Resources/Icons/Icons.xcassets/Icons/Category/selectedWorld.imageset/selectedWorld@2x.png
  Projects/DesignSystem/Resources/Icons/Icons.xcassets/Icons/Category/selectedWorld.imageset/selectedWorld@3x.png
  Projects/DesignSystem/Resources/Icons/Icons.xcassets/Icons/Category/society.imageset/Contents.json
  Projects/DesignSystem/Resources/Icons/Icons.xcassets/Icons/Category/society.imageset/society.svg
  Projects/DesignSystem/Resources/Icons/Icons.xcassets/Icons/Category/society.imageset/society@1x.png
  Projects/DesignSystem/Resources/Icons/Icons.xcassets/Icons/Category/society.imageset/society@2x.png
  Projects/DesignSystem/Resources/Icons/Icons.xcassets/Icons/Category/society.imageset/society@3x.png
  Projects/DesignSystem/Resources/Icons/Icons.xcassets/Icons/Category/world.imageset/Contents.json
  Projects/DesignSystem/Resources/Icons/Icons.xcassets/Icons/Category/world.imageset/world.svg
  Projects/DesignSystem/Resources/Icons/Icons.xcassets/Icons/Category/world.imageset/world@1x.png
  Projects/DesignSystem/Resources/Icons/Icons.xcassets/Icons/Category/world.imageset/world@2x.png
  Projects/DesignSystem/Resources/Icons/Icons.xcassets/Icons/Category/world.imageset/world@3x.png
Labels: 디자인, ⭐️⭐️⭐️ㅤ

#211 기능: 서버 변경사항 반영
  Projects/Core/Services/MyPage/MyPageAPI.swift
  Projects/Features/Scene/LongStorageScene/LongStorageNewsList/LongShortsItem/LongShortsCardView.swift
  Projects/Features/Scene/NewsCardScene/NewsList/NewsCard/NewsCardView.swift
Labels: 기능

#214 기능: 마이페이지 새로고침 추가
  Projects/Features/Scene/TabBarScene/TabBar/TabBarCore.swift
Labels: ⭐️⭐️⭐️ㅤ

#215 :bookmark: v1.3.0-202308110128
  Projects/App/Info.plist
  Projects/App/xcconfigs/SeeYouAgain.shared.xcconfig
Labels: 인프라
