Repository mash-up-kr/SeeYouAgain_iOS, pull requests merged in 2023-06, with the labels that each got.

#17 기능: 폰트 리소스 추가 및 수정
  Projects/Core/Services/_Foundation/NetworkEventLogger.swift
  Tuist/ResourceSynthesizers/Fonts.stencil
Labels: 기능

#21 기능: 버블 DS 모듈 생성
  Projects/Core/Common/Category/CategoryType.swift
  Projects/DesignSystem/Sources/Views/Bubble/BubbleView.swift
  Projects/DesignSystem/Sources/Views/Bubble/InnerShadow.swift
  Projects/DesignSystem/Sources/Views/Bubble/OptionalShadow.swift
Labels: 기능

#26 기능: 배경 컴포넌트 생성
  Projects/DesignSystem/Sources/Views/Background/ShortsBackgroundView.swift
  Projects/DesignSystem/Sources/Views/Bubble/BubbleView.swift
  Projects/DesignSystem/Sources/Views/Bubble/InnerShadow.swift
  Projects/Features/Scene/SplashScene/Splash/SplashView.swift
Labels: 기능, ⭐️⭐️ㅤ

#30 기능: 카테고리 화면 구현
  Projects/App/Sources/AppView/AppView.swift
  Projects/Core/Common/Category/CategoryType.swift
  Projects/Core/Services/UserDefaults/UserDefaultsService.swift
  Projects/DesignSystem/Sources/Views/Button/BottomButton.swift
  Projects/Features/Coordinator/AppCoordinator/AppCoordinatorCore.swift
  Projects/Features/Coordinator/AppCoordinator/AppScreenCore.swift
  Projects/Features/Scene/SetCategoryScene/SetCategory/SetCategoryCore.swift
  Projects/Features/Scene/SetCategoryScene/SetCategory/SetCategoryView.swift
  Projects/Features/Scene/SplashScene/Splash/SplashCore.swift
  Projects/Features/Scene/SplashScene/Splash/SplashView.swift
Labels: ⭐️⭐️ㅤ

#31 기능: 메인 카테고리 뱃지 및 바텀 시트 구현
  Projects/Core/Common/Extensions/View+extensions.swift
  Projects/Core/Models/Main/Category.swift
  Projects/DesignSystem/Resources/Icons/Icons.xcassets/Icons/Main/Badge/Contents.json
  Projects/DesignSystem/Resources/Icons/Icons.xcassets/Icons/Main/Badge/badge.imageset/Contents.json
  Projects/DesignSystem/Resources/Icons/Icons.xcassets/Icons/Main/Badge/badge.imageset/category_icon.svg
  Projects/DesignSystem/Resources/Icons/Icons.xcassets/Icons/Main/Badge/badge_detail.imageset/Contents.json
  Projects/DesignSystem/Resources/Icons/Icons.xcassets/Icons/Main/Badge/badge_detail.imageset/badge_detail.svg
  Projects/DesignSystem/Resources/Icons/Icons.xcassets/Icons/Main/Contents.json
  Projects/DesignSystem/Sources/Views/Background/BlurEffect.swift
  Projects/DesignSystem/Sources/Views/BottomSheet/BottomSheet.swift
  Projects/Features/Coordinator/AppCoordinator/AppCoordinatorCore.swift
  Projects/Features/Scene/MainScene/Main/Category/CategoriesView.swift
  Projects/Features/Scene/MainScene/Main/Category/CategoryBadgeButton.swift
  Projects/Features/Scene/MainScene/Main/Category/CategoryDetailButton.swift
  Projects/Features/Scene/MainScene/Main/Category/CategoryType.swift
  Projects/Features/Scene/MainScene/Main/MainCore.swift
  Projects/Features/Scene/MainScene/Main/MainView.swift
  Projects/Features/Scene/Project.swift
  Projects/Features/Scene/TabBarScene/BottomSheet/BottomSheetCore.swift
  Projects/Features/Scene/TabBarScene/BottomSheet/CategoryBottomSheet.swift
  Projects/Features/Scene/TabBarScene/TabBar/TabBarCore.swift
  Projects/Features/Scene/TabBarScene/TabBar/TabBarView.swift
Labels: 기능, ⭐️ㅤ

#34 기능: 오픈소스 라이선스 항목 설정 추가
  Projects/App/Resources/Settings.bundle/Root.plist
  Projects/App/Resources/Settings.bundle/Shorts.latest_result.txt
  Projects/App/Resources/Settings.bundle/Shorts.plist
  Projects/App/Resources/Settings.bundle/Shorts/Alamofire.plist
  Projects/App/Resources/Settings.bundle/Shorts/CombineExt.plist
  Projects/App/Resources/Settings.bundle/Shorts/FlowStacks.plist
  Projects/App/Resources/Settings.bundle/Shorts/Nuke.plist
  Projects/App/Resources/Settings.bundle/Shorts/TCACoordinators.plist
  Projects/App/Resources/Settings.bundle/Shorts/combine-schedulers.plist
  Projects/App/Resources/Settings.bundle/Shorts/swift-case-paths.plist
  Projects/App/Resources/Settings.bundle/Shorts/swift-collections.plist
  Projects/App/Resources/Settings.bundle/Shorts/swift-composable-architecture.plist
  Projects/App/Resources/Settings.bundle/Shorts/swift-custom-dump.plist
  Projects/App/Resources/Settings.bundle/Shorts/swift-identified-collections.plist
  Projects/App/Resources/Settings.bundle/Shorts/xctest-dynamic-overlay.plist
  Projects/App/Resources/Settings.bundle/en.lproj/Root.strings
Labels: 기능, ⭐️ㅤ

#36 기능: 토스트 컴포넌트 구현
  Projects/App/Sources/AppView/AppView.swift
  Projects/DesignSystem/Resources/Icons/Icons.xcassets/Icons/Toast/Contents.json
  Projects/DesignSystem/Resources/Icons/Icons.xcassets/Icons/Toast/toast_blue.imageset/Contents.json
  Projects/DesignSystem/Resources/Icons/Icons.xcassets/Icons/Toast/toast_blue.imageset/toast_blue.svg
  Projects/DesignSystem/Resources/Icons/Icons.xcassets/Icons/Toast/toast_red.imageset/Contents.json
  Projects/DesignSystem/Resources/Icons/Icons.xcassets/Icons/Toast/toast_red.imageset/toast_red.svg
  Projects/DesignSystem/Sources/Views/Toast/Toast.swift
  Projects/DesignSystem/Sources/Views/Toast/ToastModifier.swift
  Projects/DesignSystem/Sources/Views/Toast/ToastType.swift
  Projects/Features/Coordinator/AppCoordinator/AppCoordinatorCore.swift
  Projects/Features/Coordinator/AppCoordinator/AppScreenCore.swift
  Projects/Features/Scene/SetCategoryScene/SetCategory/SetCategoryCore.swift
  Projects/Features/Scene/SetCategoryScene/SetCategory/SetCategoryView.swift
Labels: 기능

#38 기능: 스크롤 뷰 구현
  Projects/Features/Scene/MainScene/Main/Letter/LetterScrollCore.swift
  Projects/Features/Scene/MainScene/Main/Letter/LetterScrollView.swift
  Projects/Features/Scene/MainScene/Main/MainCore.swift
  Projects/Features/Scene/MainScene/Main/MainView.swift
Labels: 기능, ⭐️ㅤ

#42 리팩터: API 코드 리팩토링 및 카테고리 API 연동
  Projects/Core/Models/Network/Category/RequestDTO/SaveCategoryDTO.swift
  Projects/Core/Models/Network/Category/ResponseDTO/CategoryDTO.swift
  Projects/Core/Services/Category/CategoryAPI.swift
  Projects/Core/Services/Category/CategoryService.swift
  Projects/Core/Services/User/UserService.swift
  Projects/Core/Services/_Foundation/Provider.swift
  Projects/Core/Services/_Foundation/ProviderError.swift
  Projects/Core/Services/_Foundation/ResponseDTO.swift
  Projects/Features/Scene/SplashScene/Splash/SplashCore.swift
Labels: 수정, ⭐️⭐️⭐️ㅤ

#44 기능: 편지 애니메이션 구현
  Projects/DesignSystem/Resources/Images/Images.xcassets/Main/Contents.json
  Projects/DesignSystem/Resources/Images/Images.xcassets/Main/img_politics.imageset/Contents.json
  Projects/DesignSystem/Resources/Images/Images.xcassets/Main/img_politics.imageset/img_politics.svg
  Projects/DesignSystem/Resources/Images/Images.xcassets/Main/letter.imageset/Contents.json
  Projects/DesignSystem/Resources/Images/Images.xcassets/Main/letter.imageset/letter.svg
  Projects/DesignSystem/Resources/Images/Images.xcassets/Main/letter_background.imageset/Contents.json
  Projects/DesignSystem/Resources/Images/Images.xcassets/Main/letter_background.imageset/letter_background.svg
  Projects/Features/Scene/MainScene/Main/Letter/Components/LetterBottom.swift
  Projects/Features/Scene/MainScene/Main/Letter/Components/LetterPaper.swift
  Projects/Features/Scene/MainScene/Main/Letter/Components/LetterSide.swift
  Projects/Features/Scene/MainScene/Main/Letter/Components/LetterTop.swift
  Projects/Features/Scene/MainScene/Main/Letter/Components/LetterView.swift
  Projects/Features/Scene/MainScene/Main/Letter/Components/OpaqueShape.swift
  Projects/Features/Scene/MainScene/Main/Letter/LetterScrollCore.swift
  Projects/Features/Scene/MainScene/Main/Letter/LetterScrollView.swift
Labels: 기능, ⭐️ㅤ

#50 디자인: 변경된 메인 디자인 적용
  Projects/DesignSystem/Resources/Colors/Colors.xcassets/Background/Contents.json
  Projects/DesignSystem/Resources/Colors/Colors.xcassets/Background/light_blue.colorset/Contents.json
  Projects/DesignSystem/Resources/Colors/Colors.xcassets/Background/sky_blue.colorset/Contents.json
  Projects/DesignSystem/Resources/Icons/Icons.xcassets/Icons/Main/Badge/badge.imageset/category_icon.svg
  Projects/DesignSystem/Resources/Icons/Icons.xcassets/Icons/Main/Badge/badge_detail.imageset/badge_detail.svg
  Projects/DesignSystem/Resources/Icons/Icons.xcassets/Icons/Main/CaretDown.imageset/CaretDown.svg
  Projects/DesignSystem/Resources/Icons/Icons.xcassets/Icons/Main/CaretDown.imageset/Contents.json
  Projects/DesignSystem/Resources/Images/Images.xcassets/Main/main_title.imageset/Contents.json
  Projects/DesignSystem/Resources/Images/Images.xcassets/Main/main_title.imageset/main_title.svg
  Projects/Features/Scene/MainScene/Main/Category/CategoriesView.swift
  Projects/Features/Scene/MainScene/Main/Category/CategoryBadge.swift
  Projects/Features/Scene/MainScene/Main/Category/CategoryBadgeButton.swift
  Projects/Features/Scene/MainScene/Main/Category/CategoryDetailButton.swift
  Projects/Features/Scene/MainScene/Main/Category/CategoryType.swift
  Projects/Features/Scene/MainScene/Main/Letter/LetterScrollCore.swift
  Projects/Features/Scene/MainScene/Main/Letter/LetterScrollView.swift
  Projects/Features/Scene/MainScene/Main/MainCore.swift
  Projects/Features/Scene/MainScene/Main/MainView.swift
  Projects/Features/Scene/TabBarScene/BottomSheet/CategoryBottomSheet.swift
Labels: 디자인, ⭐️⭐️ㅤ

#52 디자인: 탭바 디자인 수정사항 적용
  Projects/DesignSystem/Resources/Icons/Icons.xcassets/Icons/Tab/default_fire.imageset/default_fire.svg
  Projects/DesignSystem/Resources/Icons/Icons.xcassets/Icons/Tab/default_house.imageset/default_house.svg
  Projects/DesignSystem/Resources/Icons/Icons.xcassets/Icons/Tab/default_user.imageset/default_user.svg
  Projects/DesignSystem/Resources/Icons/Icons.xcassets/Icons/Tab/selected_fire.imageset/selected_fire.svg
  Projects/DesignSystem/Resources/Icons/Icons.xcassets/Icons/Tab/selected_house.imageset/selected_house.svg
  Projects/DesignSystem/Resources/Icons/Icons.xcassets/Icons/Tab/selected_user.imageset/selected_user.svg
  Projects/DesignSystem/Sources/Views/Navigation/TopNavigationBar.swift
  Projects/Features/Scene/TabBarScene/TabBar/ShortsTabBarView.swift
  Projects/Features/Scene/TabBarScene/TabBar/TabBarCore.swift
  Projects/Features/Scene/TabBarScene/TabBar/TabBarView.swift
Labels: 디자인, ⭐️⭐️ㅤ

#53 기능: 카테고리 선택 API 구현 연동 및 카테고리 설정 화면 마무리
  Projects/App/Sources/AppView/AppView.swift
  Projects/Core/Common/Category/CategoryType.swift
  Projects/Core/Models/Network/Category/RequestDTO/SaveCategoryRequestDTO.swift
  Projects/Core/Models/Network/Category/ResponseDTO/CategoryDTO.swift
  Projects/Core/Models/Network/Category/ResponseDTO/SaveCategoryResponseDTO.swift
  Projects/Core/Services/Category/CategoryAPI.swift
  Projects/Core/Services/Category/CategoryService.swift
  Projects/Core/Services/UserDefaults/UserDefaultsService.swift
  Projects/DesignSystem/Resources/Icons/Icons.xcassets/Icons/Category/Contents.json
  Projects/DesignSystem/Resources/Icons/Icons.xcassets/Icons/Category/comingSoon.imageset/Contents.json
  Projects/DesignSystem/Resources/Icons/Icons.xcassets/Icons/Category/comingSoon.imageset/comingSoon.svg
  Projects/DesignSystem/Resources/Icons/Icons.xcassets/Icons/Category/culture.imageset/Contents.json
  Projects/DesignSystem/Resources/Icons/Icons.xcassets/Icons/Category/culture.imageset/culture.svg
  Projects/DesignSystem/Resources/Icons/Icons.xcassets/Icons/Category/economics.imageset/Contents.json
  Projects/DesignSystem/Resources/Icons/Icons.xcassets/Icons/Category/economics.imageset/economics.svg
  Projects/DesignSystem/Resources/Icons/Icons.xcassets/Icons/Category/politics.imageset/Contents.json
  Projects/DesignSystem/Resources/Icons/Icons.xcassets/Icons/Category/politics.imageset/politics.svg
  Projects/DesignSystem/Resources/Icons/Icons.xcassets/Icons/Category/science.imageset/Contents.json
  Projects/DesignSystem/Resources/Icons/Icons.xcassets/Icons/Category/science.imageset/science.svg
  Projects/DesignSystem/Resources/Icons/Icons.xcassets/Icons/Category/selectedCulture.imageset/Contents.json
  Projects/DesignSystem/Resources/Icons/Icons.xcassets/Icons/Category/selectedCulture.imageset/selectedCulture.svg
  Projects/DesignSystem/Resources/Icons/Icons.xcassets/Icons/Category/selectedEconomics.imageset/Contents.json
  Projects/DesignSystem/Resources/Icons/Icons.xcassets/Icons/Category/selectedEconomics.imageset/selectedEconomics.svg
  Projects/DesignSystem/Resources/Icons/Icons.xcassets/Icons/Category/selectedPolitics.imageset/Contents.json
  Projects/DesignSystem/Resources/Icons/Icons.xcassets/Icons/Category/selectedPolitics.imageset/selectedPolitics.svg
  Projects/DesignSystem/Resources/Icons/Icons.xcassets/Icons/Category/selectedScience.imageset/Contents.json
  Projects/DesignSystem/Resources/Icons/Icons.xcassets/Icons/Category/selectedScience.imageset/selectedScience.svg
  Projects/DesignSystem/Resources/Icons/Icons.xcassets/Icons/Category/selectedSociety.imageset/Contents.json
  Projects/DesignSystem/Resources/Icons/Icons.xcassets/Icons/Category/selectedSociety.imageset/selectedSociety.svg
  Projects/DesignSystem/Resources/Icons/Icons.xcassets/Icons/Category/selectedWorld.imageset/Contents.json
  Projects/DesignSystem/Resources/Icons/Icons.xcassets/Icons/Category/selectedWorld.imageset/selectedWorld.svg
  Projects/DesignSystem/Resources/Icons/Icons.xcassets/Icons/Category/society.imageset/Contents.json
  Projects/DesignSystem/Resources/Icons/Icons.xcassets/Icons/Category/society.imageset/society.svg
  Projects/DesignSystem/Resources/Icons/Icons.xcassets/Icons/Category/world.imageset/Contents.json
  Projects/DesignSystem/Resources/Icons/Icons.xcassets/Icons/Category/world.imageset/world.svg
  Projects/DesignSystem/Sources/Views/Button/BottomButton.swift
  Projects/Features/Coordinator/AppCoordinator/AppCoordinatorCore.swift
  Projects/Features/Coordinator/AppCoordinator/AppScreenCore.swift
  Projects/Features/Scene/SetCategoryScene/SetCategory/SetCategoryCore.swift
  Projects/Features/Scene/SetCategoryScene/SetCategory/SetCategoryView.swift
Labels: 기능, ⭐️⭐️ㅤ

#56 기능: 웹 뷰 구현
  Projects/DesignSystem/Sources/Views/Navigation/TopNavigationBar.swift
  Projects/DesignSystem/Sources/Views/ShortsWebView/ShortsWebView.swift
  Projects/Features/Scene/Project.swift
  Projects/Features/Scene/WebScene/Web/WebCore.swift
  Projects/Features/Scene/WebScene/Web/WebView.swift
Labels: 기능, ⭐️⭐️ㅤ

#61 기능: 로딩 인디케이터 구현
  Projects/App/Sources/Lifecycle/AppDelegate.swift
  Projects/DesignSystem/Sources/Views/Loading/LoadingView.swift
  Projects/DesignSystem/Sources/Views/Loading/LoadingWindow.swift
Labels: 기능, ⭐️ㅤ

#64 리팩터: 스플래쉬 후 이동 로직 변경
  Projects/Features/Coordinator/AppCoordinator/AppCoordinatorCore.swift
  Projects/Features/Scene/SetCategoryScene/SetCategory/SetCategoryCore.swift
  Projects/Features/Scene/SplashScene/Splash/SplashCore.swift
  Projects/Features/Scene/SplashScene/Splash/SplashView.swift
Labels: 수정, ⭐️ㅤ

#58 기능: 오늘의 숏스 화면 구현
  Projects/DesignSystem/Resources/Icons/Icons.xcassets/Icons/Tab/default_fire.imageset/default_fire.svg
  Projects/DesignSystem/Resources/Icons/Icons.xcassets/Icons/Tab/default_user.imageset/default_user.svg
  Projects/DesignSystem/Resources/Icons/Icons.xcassets/Icons/Tab/selected_fire.imageset/selected_fire.svg
  Projects/DesignSystem/Resources/Icons/Icons.xcassets/Icons/Tab/selected_user.imageset/selected_user.svg
  Projects/DesignSystem/Resources/Images/Images.xcassets/earth_card.imageset/Contents.json
  Projects/DesignSystem/Resources/Images/Images.xcassets/earth_card.imageset/earth_card.svg
  Projects/DesignSystem/Sources/Views/Toggle/ShortsToggleStyle.swift
  Projects/Features/Coordinator/AppCoordinator/AppCoordinatorCore.swift
  Projects/Features/Coordinator/AppCoordinator/AppScreenCore.swift
  Projects/Features/Coordinator/MyPageCoordinator/MyPageCoordinatorCore.swift
  Projects/Features/Coordinator/MyPageCoordinator/MyPageScreenCore.swift
  Projects/Features/Coordinator/NewsCardCoordinator/NewsCardCoordinatorCore.swift
  Projects/Features/Coordinator/NewsCardCoordinator/NewsCardCoordinatorView.swift
  Projects/Features/Coordinator/ShortStorageCoordinator/ShortStorageCoordinatorCore.swift
  Projects/Features/Coordinator/ShortStorageCoordinator/ShortStorageScreenCore.swift
  Projects/Features/Scene/NewsCardScene/NewsList/NewsListCore.swift
  Projects/Features/Scene/NewsCardScene/NewsList/NewsListView.swift
  Projects/Features/Scene/ShortStorageScene/ShortStorageNewsList/ShortStorageNewsListCore.swift
  Projects/Features/Scene/ShortStorageScene/ShortStorageNewsList/ShortStorageNewsListView.swift
  Projects/Features/Scene/ShortStorageScene/ShortStorageNewsList/TodayShortsItem/TodayShortsCardCore.swift
  Projects/Features/Scene/ShortStorageScene/ShortStorageNewsList/TodayShortsItem/TodayShortsCardView.swift
  Projects/Features/Scene/ShortStorageScene/ShortStorageNewsList/TodayShortsItem/TodayShortsItemCore.swift
  Projects/Features/Scene/ShortStorageScene/ShortStorageNewsList/TodayShortsItem/TodayShortsItemView.swift
  Projects/Features/Scene/TabBarScene/TabBar/TabBarCore.swift
Labels: 기능, ⭐️⭐️ㅤ

#67 기능: 키워드 내 뉴스 리스트, 숏스 추가 완료 화면 구현
  Projects/DesignSystem/Resources/Icons/Icons.xcassets/Icons/My/icon_calendar.imageset/icon_calendar.svg
  Projects/DesignSystem/Sources/Views/Category/CategoryView.swift
  Projects/Features/Coordinator/AppCoordinator/AppCoordinatorCore.swift
  Projects/Features/Coordinator/AppCoordinator/AppScreenCore.swift
  Projects/Features/Coordinator/NewsCardCoordinator/NewsCardCoordinatorCore.swift
  Projects/Features/Coordinator/NewsCardCoordinator/NewsCardCoordinatorView.swift
  Projects/Features/Coordinator/NewsCardCoordinator/NewsCardScreenCore.swift
  Projects/Features/Coordinator/Project.swift
  Projects/Features/Coordinator/SettingCoordinator/SettingScreenCore.swift
  Projects/Features/Coordinator/ShortStorageCoordinator/ShortStorageCoordinatorCore.swift
  Projects/Features/Scene/NewsCardScene/NewsList/NewsCard/NewsCardCore.swift
  Projects/Features/Scene/NewsCardScene/NewsList/NewsCard/NewsCardView.swift
  Projects/Features/Scene/NewsCardScene/NewsList/NewsListCore.swift
  Projects/Features/Scene/NewsCardScene/NewsList/NewsListView.swift
  Projects/Features/Scene/NewsCardScene/NewsList/ShortsComplete/ShortsCompleteCore.swift
  Projects/Features/Scene/NewsCardScene/NewsList/ShortsComplete/ShortsCompleteView.swift
  Projects/Features/Scene/ShortStorageScene/ShortStorageNewsList/ShortStorageNewsListCore.swift
  Projects/Features/Scene/ShortStorageScene/ShortStorageNewsList/ShortStorageNewsListView.swift
  Projects/Features/Scene/TabBarScene/BottomSheet/BottomSheetCore.swift
  Projects/Features/Scene/TabBarScene/BottomSheet/CategoryBottomSheet.swift
  Projects/Features/Scene/TabBarScene/TabBar/TabBarCore.swift
  Projects/Features/Scene/TabBarScene/TabBar/TabBarView.swift
Labels: 기능, ⭐️⭐️ㅤ

#68 기능: 커서 페이징 구현
  Projects/Features/Coordinator/MainCoordinator/MainCoordinatorCore.swift
  Projects/Features/Coordinator/MainCoordinator/MainScreenCore.swift
  Projects/Features/Scene/MainScene/Main/MainCore.swift
  Projects/Features/Scene/MainScene/Main/MainView.swift
  Projects/Features/Scene/MainScene/Main/NewsCard/NewsCardScrollCore.swift
  Projects/Features/Scene/MainScene/Main/NewsCard/NewsCardScrollView.swift
  Projects/Features/Scene/TabBarScene/TabBar/TabBarCore.swift
Labels: 기능, ⭐️⭐️ㅤ

#74 기능: 오래 간직할 숏스 화면 구현
  Projects/Features/Coordinator/LongStorageCoordinator/LongStorageCoordinatorCore.swift
  Projects/Features/Coordinator/LongStorageCoordinator/LongStorageCoordinatorView.swift
  Projects/Features/Coordinator/LongStorageCoordinator/LongStorageScreenCore.swift
  Projects/Features/Coordinator/Project.swift
  Projects/Features/Scene/LongStorageScene/LongStorageNewsList/LongShortsItem/LongShortsCardCore.swift
  Projects/Features/Scene/LongStorageScene/LongStorageNewsList/LongShortsItem/LongShortsCardView.swift
  Projects/Features/Scene/LongStorageScene/LongStorageNewsList/LongShortsItem/LongShortsItemCore.swift
  Projects/Features/Scene/LongStorageScene/LongStorageNewsList/LongShortsItem/LongShortsItemView.swift
  Projects/Features/Scene/LongStorageScene/LongStorageNewsList/LongStorageNewsListCore.swift
  Projects/Features/Scene/LongStorageScene/LongStorageNewsList/LongStorageNewsListView.swift
  Projects/Features/Scene/LongStorageScene/LongStorageNewsList/LongStorageStub.swift
  Projects/Features/Scene/ShortStorageScene/ShortStorageNewsList/ShortStorageNewsListView.swift
Labels: 기능, ⭐️⭐️ㅤ

#73 기능: 토스트 메세지 추가
  Projects/DesignSystem/Sources/Views/BottomSheet/BottomSheet.swift
  Projects/Features/Scene/TabBarScene/TabBar/TabBarView.swift
Labels: 기능, ⭐️⭐️ㅤ

#75 기능: 디자인 디테일 수정
  Projects/DesignSystem/Resources/Colors/Colors.xcassets/MyPage/Contents.json
  Projects/DesignSystem/Resources/Colors/Colors.xcassets/MyPage/mypage_border.colorset/Contents.json
  Projects/Features/Scene/MyPageScene/MyPage/MyInfo/MyShortsView.swift
  Projects/Features/Scene/MyPageScene/MyPage/MyPageView.swift
Labels: 디자인, ⭐️⭐️ㅤ

#78 기능: 오늘의 숏스 저장 애니메이션 및 API 연결
  Projects/Core/Models/Network/NewsCard/RequestDTO/SaveNewsCardRequestDTO.swift
  Projects/Core/Services/NewsCard/NewsCardAPI.swift
  Projects/Core/Services/NewsCard/NewsCardService.swift
  Projects/Core/Services/UserDefaults/UserDefaultsService.swift
  Projects/Features/Coordinator/AppCoordinator/AppScreenCore.swift
  Projects/Features/Coordinator/MainCoordinator/MainCoordinatorCore.swift
  Projects/Features/Coordinator/MainCoordinator/MainScreenCore.swift
  Projects/Features/Scene/MainScene/Main/MainCore.swift
  Projects/Features/Scene/MainScene/Main/MainView.swift
  Projects/Features/Scene/MainScene/Main/NewsCard/NewsCardCore.swift
  Projects/Features/Scene/MainScene/Main/NewsCard/NewsCardScrollCore.swift
  Projects/Features/Scene/MainScene/Main/NewsCard/NewsCardView.swift
  Projects/Features/Scene/MainScene/Main/SaveGuide/SaveGuideCore.swift
  Projects/Features/Scene/MainScene/Main/SaveGuide/SaveGuideView.swift
  Projects/Features/Scene/SetCategoryScene/SetCategory/SetCategoryCore.swift
  Projects/Features/Scene/SplashScene/Splash/SplashCore.swift
  Projects/Features/Scene/TabBarScene/TabBar/TabBarCore.swift
  Projects/Features/Scene/TabBarScene/TabBar/TabBarView.swift
Labels: 기능, ⭐️⭐️ㅤ

#77 기능: 핫 키워드 페이지 구현
  Projects/App/Sources/AppView/AppView.swift
  Projects/Core/Common/Extensions/Array+extensions.swift
  Projects/Core/Common/Extensions/DateFormatter+extensions.swift
  Projects/Core/Models/Network/HotKeyword/HotKeywordDTO.swift
  Projects/Core/Services/HotKeyword/HotKeywordAPI.swift
  Projects/Core/Services/HotKeyword/HotKeywordService.swift
  Projects/DesignSystem/Resources/Icons/Icons.xcassets/Icons/HotKeyword/Contents.json
  Projects/DesignSystem/Resources/Icons/Icons.xcassets/Icons/HotKeyword/hotkeyword_title.imageset/Contents.json
  Projects/DesignSystem/Resources/Icons/Icons.xcassets/Icons/HotKeyword/hotkeyword_title.imageset/hotkeyword_title.pdf
  Projects/DesignSystem/Sources/Views/Bubble/BubbleView.swift
  Projects/DesignSystem/Sources/Views/Bubble/HotKeywordPattern.swift
  Projects/DesignSystem/Sources/Views/Bubble/HotKeywordPoint.swift
  Projects/Features/Coordinator/AppCoordinator/AppCoordinatorCore.swift
  Projects/Features/Coordinator/AppCoordinator/AppScreenCore.swift
  Projects/Features/Coordinator/HotKeywordCoordinator/HotKeywordCoordinatorCore.swift
  Projects/Features/Coordinator/HotKeywordCoordinator/HotKeywordCoordinatorView.swift
  Projects/Features/Coordinator/HotKeywordCoordinator/HotKeywordScreenCore.swift
  Projects/Features/Coordinator/LongStorageCoordinator/LongStorageCoordinatorCore.swift
  Projects/Features/Coordinator/NewsCardCoordinator/NewsCardCoordinatorCore.swift
  Projects/Features/Scene/HotKeywordScene/HotKeyword/HotKeywordCore.swift
  Projects/Features/Scene/HotKeywordScene/HotKeyword/HotKeywordPointList.swift
  Projects/Features/Scene/HotKeywordScene/HotKeyword/HotKeywordView.swift
  Projects/Features/Scene/TabBarScene/TabBar/TabBarCore.swift
Labels: 기능, ⭐️⭐️ㅤ

#80 기능: 마이 화면 내 정보 조회 API 연동
  Projects/App/Sources/AppView/AppView.swift
  Projects/Core/Models/MyPage/User.swift
  Projects/Core/Models/Network/MemberInfoResponseDTO.swift
  Projects/Core/Models/Network/User/UserDTO.swift
  Projects/Core/Services/MyPage/MyPageAPI.swift
  Projects/Core/Services/MyPage/MyPageService.swift
  Projects/Features/Coordinator/AppCoordinator/AppCoordinatorCore.swift
  Projects/Features/Coordinator/AppCoordinator/AppScreenCore.swift
  Projects/Features/Coordinator/MyPageCoordinator/MyPageCoordinatorCore.swift
  Projects/Features/Coordinator/MyPageCoordinator/MyPageScreenCore.swift
  Projects/Features/Scene/MyPageScene/MyPage/MyInfo/MyInfoCore.swift
  Projects/Features/Scene/MyPageScene/MyPage/MyInfo/MyInfoView.swift
  Projects/Features/Scene/MyPageScene/MyPage/MyInfo/MyShortsCore.swift
  Projects/Features/Scene/MyPageScene/MyPage/MyInfo/MyShortsView.swift
  Projects/Features/Scene/MyPageScene/MyPage/MyPageCore.swift
  Projects/Features/Scene/MyPageScene/MyPage/MyPageView.swift
  Projects/Features/Scene/TabBarScene/TabBar/TabBarCore.swift
Labels: 기능, ⭐️⭐️ㅤ

#84 기능: 로딩 인디케이터 연결
  Projects/Features/Scene/MainScene/Main/MainCore.swift
  Projects/Features/Scene/MainScene/Main/MainView.swift
Labels: 기능

#86 버그: 카테고리 변경 로직 시퀀스 보장
  Projects/Features/Scene/MainScene/Main/MainCore.swift
Labels: 버그, ⭐️⭐️ㅤ

#81 기능: 핫 키워드 눌렀을 때, 뉴스 목록 화면 이동 구현
  Projects/Core/Models/Network/NewsCard/ResponseDTO/NewsCardsResponseDTO.swift
  Projects/Core/Services/HotKeyword/HotKeywordAPI.swift
  Projects/Core/Services/HotKeyword/HotKeywordService.swift
  Projects/Features/Coordinator/HotKeywordCoordinator/HotKeywordCoordinatorCore.swift
  Projects/Features/Coordinator/NewsCardCoordinator/NewsCardCoordinatorCore.swift
  Projects/Features/Scene/HotKeywordScene/HotKeyword/HotKeywordCore.swift
  Projects/Features/Scene/HotKeywordScene/HotKeyword/HotKeywordView.swift
  Projects/Features/Scene/NewsCardScene/NewsList/NewsCard/NewsCardCore.swift
  Projects/Features/Scene/NewsCardScene/NewsList/NewsListCore.swift
  Projects/Features/Scene/TabBarScene/TabBar/TabBarCore.swift
Labels: 기능, ⭐️⭐️ㅤ

#89 리팩터: 런치스크린 / 스플래쉬 화면 디자인 수정
  Projects/App/Resources/Assets.xcassets/launchLogo.imageset/Contents.json
  Projects/App/Resources/Assets.xcassets/launchLogo.imageset/launchLogo.png
  Projects/App/Resources/Assets.xcassets/logo.imageset/logo.pdf
  Projects/App/Resources/Assets.xcassets/shortsDescription.imageset/Contents.json
  Projects/App/Resources/Assets.xcassets/shortsDescription.imageset/shortsDescription.pdf
  Projects/App/Resources/LaunchScreen.storyboard
  Projects/DesignSystem/Resources/Images/Images.xcassets/Splash/Contents.json
  Projects/DesignSystem/Resources/Images/Images.xcassets/Splash/shorts.imageset/Contents.json
  Projects/DesignSystem/Resources/Images/Images.xcassets/Splash/shorts.imageset/launchLogo.png
  Projects/Features/Scene/SplashScene/Splash/SplashView.swift
Labels: 디자인, ⭐️ㅤ

#90 기능: 뉴스 카드 선택시 뉴스 리스트로 이동하는 로직 구현
  Projects/Core/Models/Network/NewsCard/RequestDTO/NewsRequestDTO.swift
  Projects/Core/Models/Network/NewsCard/ResponseDTO/NewsResponseDTO.swift
  Projects/Core/Services/NewsCard/NewsCardAPI.swift
  Projects/Core/Services/NewsCard/NewsCardService.swift
  Projects/Features/Coordinator/MainCoordinator/MainCoordinatorCore.swift
  Projects/Features/Coordinator/MainCoordinator/MainCoordinatorView.swift
  Projects/Features/Coordinator/MainCoordinator/MainScreenCore.swift
  Projects/Features/Coordinator/Project.swift
  Projects/Features/Scene/MainScene/Main/MainCore.swift
  Projects/Features/Scene/MainScene/Main/NewsCard/Components/LetterPaper.swift
  Projects/Features/Scene/MainScene/Main/NewsCard/NewsCardCore.swift
  Projects/Features/Scene/MainScene/Main/NewsCard/NewsCardView.swift
  Projects/Features/Scene/TabBarScene/TabBar/TabBarCore.swift
Labels: 기능, ⭐️⭐️ㅤ

#92 기능: 저장 후 다음 뉴스카드로 자동 스크롤 구현
  Projects/Core/Models/Network/NewsCard/RequestDTO/SaveNewsCardRequestDTO.swift
  Projects/Core/Models/Network/NewsCard/ResponseDTO/NewsResponseDTO.swift
  Projects/Core/Services/NewsCard/NewsCardAPI.swift
  Projects/Features/Scene/MainScene/Main/MainCore.swift
  Projects/Features/Scene/MainScene/Main/NewsCard/NewsCardScrollCore.swift
Labels: 기능, ⭐️⭐️ㅤ

#94 디자인: 편지 디자인 변경
  Projects/Features/Scene/MainScene/Main/NewsCard/Components/LetterBottom.swift
  Projects/Features/Scene/MainScene/Main/NewsCard/Components/LetterSide.swift
  Projects/Features/Scene/MainScene/Main/NewsCard/Components/LetterTop.swift
  Projects/Features/Scene/MainScene/Main/NewsCard/Components/OpaqueShape.swift
Labels: 디자인, ⭐️⭐️ㅤ

#97 리팩터: 설정 > 최신버전 관련 디자인 및 기능 변경
  Projects/Core/Services/AppVersion/AppVersionService.swift
  Projects/Features/Scene/SettingScene/Setting/SettingCore.swift
  Projects/Features/Scene/SettingScene/Setting/SettingView.swift
Labels: 디자인, ⭐️ㅤ

#98 수정: 핫키워드 뉴스리스트 진입시 탭바 숨기기 및 핫키워드 뉴스리스트 조회 삭제
  Projects/Core/Common/Extensions/DateFormatter+extensions.swift
  Projects/Core/Models/Network/HotKeyword/HotKeywordDTO.swift
  Projects/Core/Services/HotKeyword/HotKeywordAPI.swift
  Projects/Core/Services/HotKeyword/HotKeywordService.swift
  Projects/Features/Coordinator/HotKeywordCoordinator/HotKeywordCoordinatorCore.swift
  Projects/Features/Coordinator/Project.swift
  Projects/Features/Scene/HotKeywordScene/HotKeyword/HotKeywordCore.swift
  Projects/Features/Scene/NewsCardScene/NewsList/NewsCard/NewsCardCore.swift
  Projects/Features/Scene/NewsCardScene/NewsList/NewsListCore.swift
  Projects/Features/Scene/TabBarScene/TabBar/TabBarCore.swift
Labels: 버그, 수정, ⭐️⭐️ㅤ

#100 기능: 버블 뷰 블러 추가
  Projects/Core/Models/Network/HotKeyword/HotKeywordDTO.swift
  Projects/DesignSystem/Sources/Views/Bubble/BubbleView.swift
  Projects/DesignSystem/Sources/Views/Bubble/HotKeywordPattern.swift
  Projects/DesignSystem/Sources/Views/Bubble/HotKeywordPoint.swift
  Projects/DesignSystem/Sources/Views/Bubble/InnerShadow.swift
  Projects/DesignSystem/Sources/Views/Bubble/OptionalShadow.swift
Labels: 디자인

#101 삭제 애니메이션 구현 및 애니메이션 속도 조정
  Projects/Features/Coordinator/AppCoordinator/AppCoordinatorCore.swift
  Projects/Features/Coordinator/MainCoordinator/MainCoordinatorCore.swift
  Projects/Features/Coordinator/MainCoordinator/MainCoordinatorView.swift
  Projects/Features/Coordinator/MainCoordinator/MainScreenCore.swift
  Projects/Features/Coordinator/Project.swift
  Projects/Features/Scene/MainScene/Main/MainView.swift
  Projects/Features/Scene/MainScene/Main/NewsCard/NewsCardCore.swift
  Projects/Features/Scene/MainScene/Main/NewsCard/NewsCardScrollCore.swift
  Projects/Features/Scene/MainScene/Main/NewsCard/NewsCardScrollView.swift
  Projects/Features/Scene/MainScene/Main/NewsCard/NewsCardView.swift
  Projects/Features/Scene/TabBarScene/TabBar/TabBarCore.swift
Labels: 기능, ⭐️⭐️ㅤ

#102 리팩터: 핫 키워드에서 뉴스 리스트 들어가는 진입점, 앱 코디네이터로 변경
  Projects/Features/Coordinator/AppCoordinator/AppCoordinatorCore.swift
  Projects/Features/Coordinator/HotKeywordCoordinator/HotKeywordCoordinatorCore.swift
  Projects/Features/Coordinator/HotKeywordCoordinator/HotKeywordCoordinatorView.swift
  Projects/Features/Coordinator/HotKeywordCoordinator/HotKeywordScreenCore.swift
  Projects/Features/Coordinator/Project.swift
  Projects/Features/Scene/TabBarScene/TabBar/TabBarCore.swift
Labels: 수정, ⭐️⭐️ㅤ

#103 버그: Web import 제거 및 오래 간직할 숏스 화면 동작 로직 수정
  Projects/Features/Coordinator/AppCoordinator/AppCoordinatorCore.swift
  Projects/Features/Coordinator/LongStorageCoordinator/LongStorageCoordinatorCore.swift
  Projects/Features/Coordinator/LongStorageCoordinator/LongStorageCoordinatorView.swift
  Projects/Features/Coordinator/LongStorageCoordinator/LongStorageScreenCore.swift
  Projects/Features/Coordinator/NewsCardCoordinator/NewsCardCoordinatorCore.swift
  Projects/Features/Scene/LongStorageScene/LongStorageNewsList/LongShortsItem/LongShortsCardCore.swift
  Projects/Features/Scene/NewsCardScene/NewsList/NewsCard/NewsCardCore.swift
Labels: 버그, ⭐️⭐️⭐️ㅤ
