Repository mash-up-kr/SeeYouAgain_iOS, pull requests merged in 2023-07, with the labels that each got.

#105 리팩터: 설정 > 앱 최신 정보 정렬 수정
  Projects/Features/Scene/SettingScene/Setting/SettingView.swift
Labels: 수정, ⭐️ㅤ

#108 리팩터: 카테고리 선택 화면 내 바텀 버튼 문구 수정
  Projects/Features/Scene/SetCategoryScene/SetCategory/SetCategoryCore.swift
  Projects/Features/Scene/SetCategoryScene/SetCategory/SetCategoryView.swift
Labels: 디자인, ⭐️ㅤ

#111 기능: 오늘의 숏스 API 연동 외..
  Projects/Core/Common/Extensions/Date+extensions.swift
  Projects/Core/Common/Paging/FetchType.swift
  Projects/Core/Models/Main/NewsCard.swift
  Projects/Core/Models/MyPage/TodayNewsCard.swift
  Projects/Core/Models/MyPage/TodayShorts.swift
  Projects/Core/Models/Network/MyPage/MemberInfoResponseDTO.swift
  Projects/Core/Models/Network/MyPage/RequestDTO/CompleteTodayShortsRequestDTO.swift
  Projects/Core/Models/Network/MyPage/RequestDTO/DeleteTodayShortsRequestDTO.swift
  Projects/Core/Models/Network/MyPage/RequestDTO/TodayShortsRequestDTO.swift
  Projects/Core/Models/Network/MyPage/ResponseDTO/CompleteTodayShortsResponseDTO.swift
  Projects/Core/Models/Network/MyPage/ResponseDTO/TodayShortsResponseDTO.swift
  Projects/Core/Models/Network/NewsCard/RequestDTO/NewsRequestDTO.swift
  Projects/Core/Models/Network/NewsCard/ResponseDTO/NewsResponseDTO.swift
  Projects/Core/Models/News/News.swift
  Projects/Core/Services/HotKeyword/HotKeywordAPI.swift
  Projects/Core/Services/MyPage/MyPageAPI.swift
  Projects/Core/Services/MyPage/MyPageService.swift
  Projects/Core/Services/NewsCard/NewsCardAPI.swift
  Projects/Core/Services/NewsCard/NewsCardService.swift
  Projects/DesignSystem/Resources/Images/Images.xcassets/Card/Contents.json
  Projects/DesignSystem/Resources/Images/Images.xcassets/Card/card_culture.imageset/Contents.json
  Projects/DesignSystem/Resources/Images/Images.xcassets/Card/card_culture.imageset/card_culture.svg
  Projects/DesignSystem/Resources/Images/Images.xcassets/Card/card_economics.imageset/Contents.json
  Projects/DesignSystem/Resources/Images/Images.xcassets/Card/card_economics.imageset/card_economics.svg
  Projects/DesignSystem/Resources/Images/Images.xcassets/Card/card_it.imageset/Contents.json
  Projects/DesignSystem/Resources/Images/Images.xcassets/Card/card_it.imageset/card_it.svg
  Projects/DesignSystem/Resources/Images/Images.xcassets/Card/card_politics.imageset/Contents.json
  Projects/DesignSystem/Resources/Images/Images.xcassets/Card/card_politics.imageset/card_politics.svg
  Projects/DesignSystem/Resources/Images/Images.xcassets/Card/card_society.imageset/Contents.json
  Projects/DesignSystem/Resources/Images/Images.xcassets/Card/card_society.imageset/card_society.svg
  Projects/DesignSystem/Resources/Images/Images.xcassets/Card/card_world.imageset/Contents.json
  Projects/DesignSystem/Resources/Images/Images.xcassets/Card/card_world.imageset/card_world.svg
  Projects/DesignSystem/Resources/Images/Images.xcassets/earth.imageset/earth.svg
  Projects/DesignSystem/Resources/Images/Images.xcassets/earth_card.imageset/earth_card.svg
  Projects/DesignSystem/Resources/Images/Images.xcassets/image_earth.imageset/Contents.json
  Projects/DesignSystem/Resources/Images/Images.xcassets/image_earth.imageset/image_earth.svg
  Projects/Features/Coordinator/AppCoordinator/AppCoordinatorCore.swift
  Projects/Features/Coordinator/AppCoordinator/AppScreenCore.swift
  Projects/Features/Coordinator/HotKeywordCoordinator/HotKeywordScreenCore.swift
  Projects/Features/Coordinator/MyPageCoordinator/MyPageScreenCore.swift
  Projects/Features/Coordinator/NewsCardCoordinator/NewsCardCoordinatorCore.swift
  Projects/Features/Coordinator/NewsCardCoordinator/NewsCardScreenCore.swift
  Projects/Features/Coordinator/ShortStorageCoordinator/ShortStorageCoordinatorCore.swift
  Projects/Features/Coordinator/ShortStorageCoordinator/ShortStorageScreenCore.swift
  Projects/Features/Scene/LongStorageScene/LongStorageNewsList/LongStorageNewsListCore.swift
  Projects/Features/Scene/MainScene/Main/MainCore.swift
  Projects/Features/Scene/MainScene/Main/NewsCard/NewsCardCore.swift
  Projects/Features/Scene/MyPageScene/MyPage/MyPageView.swift
  Projects/Features/Scene/NewsCardScene/NewsList/NewsCard/NewsCardCore.swift
  Projects/Features/Scene/NewsCardScene/NewsList/NewsCard/NewsCardView.swift
  Projects/Features/Scene/NewsCardScene/NewsList/NewsListCore.swift
  Projects/Features/Scene/NewsCardScene/NewsList/NewsListView.swift
  Projects/Features/Scene/NewsCardScene/NewsList/ShortsComplete/ShortsCompleteCore.swift
  Projects/Features/Scene/NewsCardScene/NewsList/ShortsComplete/ShortsCompleteView.swift
  Projects/Features/Scene/ShortStorageScene/ShortStorageNewsList/ShortStorageNewsListCore.swift
  Projects/Features/Scene/ShortStorageScene/ShortStorageNewsList/ShortStorageNewsListView.swift
  Projects/Features/Scene/ShortStorageScene/ShortStorageNewsList/TodayShortsItem/TodayShortsCardCore.swift
  Projects/Features/Scene/ShortStorageScene/ShortStorageNewsList/TodayShortsItem/TodayShortsCardView.swift
Labels: 기능, ⭐️⭐️ㅤ

#114 버그: 저장 후 다음 카드로 안 넘어가는 버그 수정
  Projects/Features/Scene/MainScene/Main/NewsCard/NewsCardScrollCore.swift
Labels: 버그, ⭐️⭐️ㅤ

#116 기능: 정렬 바텀 시트 구현
  Projects/Core/Common/Core/SortBottomSheetCore.swift
  Projects/DesignSystem/Sources/Views/BottomSheet/BottomSheet.swift
  Projects/Features/Coordinator/LongStorageCoordinator/LongStorageCoordinatorCore.swift
  Projects/Features/Coordinator/LongStorageCoordinator/LongStorageScreenCore.swift
  Projects/Features/Coordinator/NewsCardCoordinator/NewsCardCoordinatorCore.swift
  Projects/Features/Coordinator/NewsCardCoordinator/NewsCardScreenCore.swift
  Projects/Features/Scene/LongStorageScene/LongStorageNewsList/LongStorageNewsListCore.swift
  Projects/Features/Scene/LongStorageScene/LongStorageNewsList/LongStorageNewsListView.swift
  Projects/Features/Scene/LongStorageScene/LongStorageNewsList/LongStorageSortBottomSheet/LongStorageSortBottomSheetContent.swift
  Projects/Features/Scene/LongStorageScene/LongStorageNewsList/LongStorageSortBottomSheet/LongStorageSortBottomSheetFooter.swift
  Projects/Features/Scene/LongStorageScene/LongStorageNewsList/LongStorageSortBottomSheet/LongStorageSortBottomSheetHeader.swift
  Projects/Features/Scene/NewsCardScene/NewsList/NewsListCore.swift
  Projects/Features/Scene/NewsCardScene/NewsList/NewsListSortBottomSheet/NewsListSortBottomSheetContent.swift
  Projects/Features/Scene/NewsCardScene/NewsList/NewsListSortBottomSheet/NewsListSortBottomSheetFooter.swift
  Projects/Features/Scene/NewsCardScene/NewsList/NewsListSortBottomSheet/NewsListSortBottomSheetHeader.swift
  Projects/Features/Scene/NewsCardScene/NewsList/NewsListView.swift
Labels: 기능, ⭐️⭐️ㅤ

#119 버그: 뉴스리스트에서 뒤로가기 할 때 탭바가 보이는 버그 수정
  Projects/Features/Coordinator/AppCoordinator/AppCoordinatorCore.swift
  Projects/Features/Coordinator/NewsCardCoordinator/NewsCardCoordinatorCore.swift
  Projects/Features/Scene/NewsCardScene/NewsList/NewsListCore.swift
  Projects/Features/Scene/NewsCardScene/NewsList/NewsListView.swift
Labels: 버그, ⭐️⭐️ㅤ

#122 버그: 오늘의숏스 편집 모드에서 아무것도 선택하지 않았을 경우 처리
  Projects/Features/Scene/ShortStorageScene/ShortStorageNewsList/ShortStorageNewsListCore.swift
Labels: 버그, ⭐️⭐️ㅤ

#123 기능: 뉴스 상세 조회, 오래 간직할 숏스 추가 API 연동
  Projects/Core/Models/Network/NewsCard/RequestDTO/SaveNewsRequestDTO.swift
  Projects/Core/Models/Network/NewsCard/ResponseDTO/CheckSavedStatusResponseDTO.swift
  Projects/Core/Services/NewsCard/NewsCardAPI.swift
  Projects/Core/Services/NewsCard/NewsCardService.swift
  Projects/Features/Coordinator/AppCoordinator/AppCoordinatorCore.swift
  Projects/Features/Coordinator/AppCoordinator/AppScreenCore.swift
  Projects/Features/Coordinator/NewsCardCoordinator/NewsCardCoordinatorCore.swift
  Projects/Features/Coordinator/NewsCardCoordinator/NewsCardScreenCore.swift
  Projects/Features/Scene/NewsCardScene/NewsList/NewsCard/NewsCardCore.swift
  Projects/Features/Scene/WebScene/Web/WebCore.swift
Labels: 기능, ⭐️⭐️ㅤ

#121 기능: 마이페이지 툴팁 구현
  Projects/Features/Scene/ShortStorageScene/ShortStorageNewsList/ShortStorageNewsListCore.swift
  Projects/Features/Scene/ShortStorageScene/ShortStorageNewsList/ShortStorageNewsListView.swift
Labels: 기능, ⭐️⭐️ㅤ

#125 오래된 숏스 카테고리 필터 바텀 시트 구현
  Projects/Core/Common/Category/CategoryType.swift
  Projects/DesignSystem/Sources/Views/BottomSheet/BottomSheet.swift
  Projects/Features/Scene/LongStorageScene/LongStorageNewsList/CategoryFilterBottomSheet/CategoryFilterBottomSheet.swift
  Projects/Features/Scene/LongStorageScene/LongStorageNewsList/CategoryFilterBottomSheet/CategoryFilterBottomSheetContent.swift
  Projects/Features/Scene/LongStorageScene/LongStorageNewsList/CategoryFilterBottomSheet/CategoryFilterBottomSheetCore.swift
  Projects/Features/Scene/LongStorageScene/LongStorageNewsList/CategoryFilterBottomSheet/CategoryFilterBottomSheetFooter.swift
  Projects/Features/Scene/LongStorageScene/LongStorageNewsList/CategoryFilterBottomSheet/CategoryFilterBottomSheetHeader.swift
  Projects/Features/Scene/LongStorageScene/LongStorageNewsList/LongStorageNewsListCore.swift
  Projects/Features/Scene/LongStorageScene/LongStorageNewsList/LongStorageNewsListView.swift
  Projects/Features/Scene/LongStorageScene/LongStorageNewsList/LongStorageSortBottomSheet/LongStorageSortBottomSheet.swift
  Projects/Features/Scene/TabBarScene/TabBar/TabBarView.swift
Labels: 기능, ⭐️⭐️ㅤ

#128 기능, 버그: 기타 이슈 처리
  Projects/Features/Coordinator/AppCoordinator/AppCoordinatorCore.swift
  Projects/Features/Coordinator/NewsCardCoordinator/NewsCardCoordinatorCore.swift
  Projects/Features/Scene/NewsCardScene/NewsList/NewsListCore.swift
  Projects/Features/Scene/TabBarScene/TabBar/TabBarCore.swift
Labels: 버그, 기능, ⭐️⭐️ㅤ

#129 기능: 마이 화면 쪽 토스트 메시지 추가
  Projects/Features/Coordinator/NewsCardCoordinator/NewsCardScreenCore.swift
  Projects/Features/Scene/LongStorageScene/LongStorageNewsList/LongStorageNewsListCore.swift
  Projects/Features/Scene/LongStorageScene/LongStorageNewsList/LongStorageNewsListView.swift
  Projects/Features/Scene/NewsCardScene/NewsList/NewsListCore.swift
  Projects/Features/Scene/ShortStorageScene/ShortStorageNewsList/ShortStorageNewsListCore.swift
  Projects/Features/Scene/ShortStorageScene/ShortStorageNewsList/ShortStorageNewsListView.swift
Labels: 기능, ⭐️⭐️ㅤ

#130 버그: 웹 뷰에서 뒤로가기 버그 수정
  Projects/Core/Common/Source/SourceType.swift
  Projects/Features/Coordinator/AppCoordinator/AppCoordinatorCore.swift
  Projects/Features/Coordinator/NewsCardCoordinator/NewsCardCoordinatorCore.swift
  Projects/Features/Scene/NewsCardScene/NewsList/NewsListCore.swift
  Projects/Features/Scene/WebScene/Web/WebCore.swift
  Projects/Features/Scene/WebScene/Web/WebView.swift
Labels: 버그

#135 기능: 이미 간직한 숏스 웹뷰 이동 시 툴팁 미표시 구현
  Projects/Features/Scene/WebScene/Web/WebCore.swift
Labels: 기능, ⭐️⭐️ㅤ

#134 버그: 메인, 핫키워드에서 진입하는 뉴스 리스트의 바텀 버튼 동작 수정
  Projects/Features/Scene/NewsCardScene/NewsList/NewsListCore.swift
  Projects/Features/Scene/NewsCardScene/NewsList/NewsListView.swift
Labels: 버그, ⭐️⭐️ㅤ

#132 기능: 오래 간직할 숏스 API 연동
  Projects/Core/Common/Date/DateType.swift
  Projects/Core/Common/Extensions/Date+extensions.swift
  Projects/Core/Models/MyPage/Pivot.swift
  Projects/Core/Models/MyPage/SavedNewsList.swift
  Projects/Core/Models/Network/News/RequestDTO/DeleteNewsRequestDTO.swift
  Projects/Core/Models/Network/News/RequestDTO/SaveNewsRequestDTO.swift
  Projects/Core/Models/Network/News/RequestDTO/SavedNewsRequestDTO.swift
  Projects/Core/Models/Network/News/ResponseDTO/NewsResponseDTO.swift
  Projects/Core/Models/Network/News/ResponseDTO/SavedNewsResponseDTO.swift
  Projects/Core/Models/Network/NewsCard/RequestDTO/NewsRequestDTO.swift
  Projects/Core/Services/MyPage/MyPageAPI.swift
  Projects/Core/Services/MyPage/MyPageService.swift
  Projects/Features/Coordinator/AppCoordinator/AppCoordinatorCore.swift
  Projects/Features/Coordinator/LongStorageCoordinator/LongStorageCoordinatorCore.swift
  Projects/Features/Coordinator/LongStorageCoordinator/LongStorageScreenCore.swift
  Projects/Features/Coordinator/MyPageCoordinator/MyPageScreenCore.swift
  Projects/Features/Coordinator/NewsCardCoordinator/NewsCardCoordinatorCore.swift
  Projects/Features/Coordinator/NewsCardCoordinator/NewsCardScreenCore.swift
  Projects/Features/Scene/LongStorageScene/LongStorageNewsList/DateFilterBottomSheet/DateFilterBottomSheet.swift
  Projects/Features/Scene/LongStorageScene/LongStorageNewsList/DateFilterBottomSheet/DateFilterBottomSheetContent.swift
  Projects/Features/Scene/LongStorageScene/LongStorageNewsList/DateFilterBottomSheet/DateFilterBottomSheetCore.swift
  Projects/Features/Scene/LongStorageScene/LongStorageNewsList/DateFilterBottomSheet/DateFilterBottomSheetFooter.swift
  Projects/Features/Scene/LongStorageScene/LongStorageNewsList/DateFilterBottomSheet/DateFilterBottomSheetHeader.swift
  Projects/Features/Scene/LongStorageScene/LongStorageNewsList/LongShortsItem/LongShortsCardCore.swift
  Projects/Features/Scene/LongStorageScene/LongStorageNewsList/LongShortsItem/LongShortsCardView.swift
  Projects/Features/Scene/LongStorageScene/LongStorageNewsList/LongStorageNewsListCore.swift
  Projects/Features/Scene/LongStorageScene/LongStorageNewsList/LongStorageNewsListView.swift
  Projects/Features/Scene/LongStorageScene/LongStorageNewsList/LongStorageStub.swift
  Projects/Features/Scene/NewsCardScene/NewsList/NewsListCore.swift
  Projects/Features/Scene/NewsCardScene/NewsList/NewsListView.swift
  Projects/Features/Scene/NewsCardScene/NewsList/ShortsComplete/ShortsCompleteCore.swift
  Projects/Features/Scene/NewsCardScene/NewsList/ShortsComplete/ShortsCompleteView.swift
  Projects/Features/Scene/ShortStorageScene/ShortStorageNewsList/ShortStorageNewsListCore.swift
  Projects/Features/Scene/ShortStorageScene/ShortStorageNewsList/ShortStorageNewsListView.swift
  Projects/Features/Scene/WebScene/Web/WebCore.swift
Labels: 기능, ⭐️⭐️ㅤ

#137 버그: 오래 간직할 숏스 카테고리 필터링 버그 수정
  Projects/Features/Scene/LongStorageScene/LongStorageNewsList/LongStorageNewsListCore.swift
Labels: 버그, ⭐️⭐️⭐️ㅤ

#138 인프라: Gemfile.lock 업데이트
  Gemfile.lock
Labels: 인프라, ⭐️⭐️⭐️ㅤ

#140 :bookmark: v1.2.0-202307071233
  Projects/App/Info.plist
  Projects/App/xcconfigs/SeeYouAgain.shared.xcconfig
Labels: 인프라

#142 버그: 카드 스크롤 버벅임 현상
  Projects/DesignSystem/Resources/Images/Images.xcassets/Main/Letter/Contents.json
  Projects/DesignSystem/Resources/Images/Images.xcassets/Main/Letter/letter_background.imageset/Contents.json
  Projects/DesignSystem/Resources/Images/Images.xcassets/Main/Letter/letter_background.imageset/letter_background.svg
  Projects/DesignSystem/Resources/Images/Images.xcassets/Main/Letter/letter_envelope.imageset/Contents.json
  Projects/DesignSystem/Resources/Images/Images.xcassets/Main/Letter/letter_envelope.imageset/letter_envelope.svg
  Projects/DesignSystem/Resources/Images/Images.xcassets/Main/Letter/letter_top.imageset/Contents.json
  Projects/DesignSystem/Resources/Images/Images.xcassets/Main/Letter/letter_top.imageset/letter_top.svg
  Projects/Features/Scene/MainScene/Main/NewsCard/Components/LetterBottom.swift
  Projects/Features/Scene/MainScene/Main/NewsCard/Components/LetterPaper.swift
  Projects/Features/Scene/MainScene/Main/NewsCard/Components/LetterSide.swift
  Projects/Features/Scene/MainScene/Main/NewsCard/Components/LetterTop.swift
  Projects/Features/Scene/MainScene/Main/NewsCard/Components/OpaqueShape.swift
  Projects/Features/Scene/MainScene/Main/NewsCard/NewsCardScrollCore.swift
  Projects/Features/Scene/MainScene/Main/NewsCard/NewsCardScrollView.swift
  Projects/Features/Scene/MainScene/Main/NewsCard/NewsCardView.swift
Labels: 버그, ⭐️⭐️ㅤ

#144 수정: 서버 URI 변경 대응
  Projects/Core/Models/Network/NewsCard/RequestDTO/HotKeywordNewsCardRequestDTO.swift
  Projects/Core/Services/MyPage/MyPageAPI.swift
  Projects/Core/Services/NewsCard/NewsCardAPI.swift
  Projects/Core/Services/NewsCard/NewsCardService.swift
Labels: 기능, ⭐️⭐️ㅤ

#145 :bookmark: v1.2.1-202307080741
  Projects/App/Info.plist
  Projects/App/xcconfigs/SeeYouAgain.shared.xcconfig
Labels: 인프라, ⭐️ㅤ

#147 버그: 스와이프 시 탭바 미노출 현상 해결
  Projects/Features/Coordinator/AppCoordinator/AppCoordinatorCore.swift
  Projects/Features/Scene/LongStorageScene/LongStorageNewsList/LongStorageNewsListCore.swift
  Projects/Features/Scene/LongStorageScene/LongStorageNewsList/LongStorageNewsListView.swift
  Projects/Features/Scene/NewsCardScene/NewsList/NewsListCore.swift
  Projects/Features/Scene/NewsCardScene/NewsList/NewsListView.swift
  Projects/Features/Scene/SettingScene/Setting/SettingCore.swift
  Projects/Features/Scene/SettingScene/Setting/SettingView.swift
  Projects/Features/Scene/ShortStorageScene/ShortStorageNewsList/ShortStorageNewsListCore.swift
  Projects/Features/Scene/ShortStorageScene/ShortStorageNewsList/ShortStorageNewsListView.swift
  Projects/Features/Scene/TabBarScene/TabBar/TabBarCore.swift
Labels: 버그, ⭐️⭐️ㅤ

#150 수정: 서버 URL 변경
  Projects/Core/Services/Category/CategoryAPI.swift
  Projects/Core/Services/HotKeyword/HotKeywordAPI.swift
  Projects/Core/Services/MyPage/MyPageAPI.swift
  Projects/Core/Services/NewsCard/NewsCardAPI.swift
Labels: 수정, ⭐️⭐️ㅤ

#153 :bookmark: v1.2.1-202307091114
  Projects/App/Info.plist
Labels: 인프라, ⭐️ㅤ

#155 버그: 1차 QA 이슈 해결
  Projects/Features/Scene/LongStorageScene/LongStorageNewsList/DateFilterBottomSheet/DateFilterBottomSheetCore.swift
  Projects/Features/Scene/LongStorageScene/LongStorageNewsList/LongStorageNewsListCore.swift
  Projects/Features/Scene/NewsCardScene/NewsList/NewsListCore.swift
  Projects/Features/Scene/TabBarScene/TabBar/TabBarCore.swift
Labels: 버그, 수정, ⭐️⭐️⭐️ㅤ

#156 버그: 중복 저장 메시지 추가
  Projects/Features/Scene/LongStorageScene/LongStorageNewsList/LongStorageNewsListCore.swift
  Projects/Features/Scene/MainScene/Main/NewsCard/NewsCardView.swift
  Projects/Features/Scene/NewsCardScene/NewsList/NewsListCore.swift
  Projects/Features/Scene/ShortStorageScene/ShortStorageNewsList/ShortStorageNewsListCore.swift
  Projects/Features/Scene/TabBarScene/TabBar/TabBarCore.swift
  Projects/Features/Scene/TabBarScene/TabBar/TabBarView.swift
Labels: 버그, ⭐️⭐️ㅤ

#158 수정: 핫키워드로 뉴스 리스트 접근 시 하단 버튼 미노출
  Projects/Features/Scene/NewsCardScene/NewsList/NewsListView.swift
Labels: 수정, ⭐️⭐️⭐️ㅤ

#159 :bookmark: v1.2.1-202307131723
  Projects/App/Info.plist
Labels: 인프라, ⭐️⭐️⭐️ㅤ

#162 :bookmark: v1.2.1-202307132001
  Projects/App/Info.plist
Labels: 인프라, ⭐️⭐️⭐️ㅤ

#167 버그: 오늘의 숏스가 보여질 때 탭바 히든 처리
  Projects/Features/Scene/TabBarScene/TabBar/TabBarCore.swift
Labels: 버그, ⭐️⭐️ㅤ

#168 기능: hot keyword 화면, background에서 foreground 됐을 때 refresh
  Projects/Features/Scene/HotKeywordScene/HotKeyword/HotKeywordCore.swift
  Projects/Features/Scene/HotKeywordScene/HotKeyword/HotKeywordView.swift
Labels: 기능, ⭐️ㅤ

#166 기능: 로딩인디케이터 추가
  Projects/Features/Scene/LongStorageScene/LongStorageNewsList/LongStorageNewsListCore.swift
  Projects/Features/Scene/LongStorageScene/LongStorageNewsList/LongStorageNewsListView.swift
  Projects/Features/Scene/MainScene/Main/MainCore.swift
  Projects/Features/Scene/MainScene/Main/MainView.swift
  Projects/Features/Scene/NewsCardScene/NewsList/NewsListCore.swift
  Projects/Features/Scene/NewsCardScene/NewsList/NewsListView.swift
  Projects/Features/Scene/ShortStorageScene/ShortStorageNewsList/ShortStorageNewsListCore.swift
  Projects/Features/Scene/ShortStorageScene/ShortStorageNewsList/ShortStorageNewsListView.swift
Labels: 기능, ⭐️ㅤ

#174 버그: 메인에서 뉴스카드 접근 시 로딩 인디케이터 처리
  Projects/Features/Scene/NewsCardScene/NewsList/NewsListCore.swift
Labels: 버그, ⭐️⭐️ㅤ

#175 버그: 오늘의 숏스를 다 읽었을 때 보여주는 뷰의 처리 수정
  Projects/Features/Scene/ShortStorageScene/ShortStorageNewsList/ShortStorageNewsListView.swift
Labels: 버그, ⭐️⭐️ㅤ

#177 기능: 뉴스 카드 썸네일 이미지 로드 완료 전 스켈레톤 이미지 구현
  Projects/Features/Scene/LongStorageScene/LongStorageNewsList/LongShortsItem/LongShortsCardView.swift
  Projects/Features/Scene/NewsCardScene/NewsList/NewsCard/NewsCardView.swift
Labels: 기능, ⭐️⭐️ㅤ

#176 수정: 핫 키워드 간헐적으로 애니메이션 동작하지 않는 현상 수정 및 탭 눌렀을때 동작 추가
  Projects/DesignSystem/Sources/Views/Bubble/BubbleView.swift
  Projects/Features/Scene/HotKeywordScene/HotKeyword/HotKeywordCore.swift
  Projects/Features/Scene/HotKeywordScene/HotKeyword/HotKeywordView.swift
  Projects/Features/Scene/TabBarScene/TabBar/TabBarCore.swift
Labels: 버그, ⭐️ㅤ

#184 수정: 30%만 스크롤 되어도 페이지가 넘어가도록 수정
  Projects/Features/Scene/MainScene/Main/NewsCard/NewsCardScrollCore.swift
Labels: 수정, ⭐️ㅤ

#185 수정: 홈 키워드 좌측 그라데이션 뷰 색상 변경
  Projects/Features/Scene/MainScene/Main/Category/CategoriesView.swift
Labels: 디자인, ⭐️ㅤ

#187 디자인: 변경된 바텀 탭 디자인 적용
  Projects/Features/Scene/TabBarScene/TabBar/ShortsTabBarView.swift
Labels: 디자인

#190 인프라: WatchOS 타겟 추가
  Projects/Core/Common/Views/ActivityView.swift
  Projects/Core/Project.swift
  Projects/Core/Services/AppVersion/AppVersionService.swift
  Projects/Core/Services/Category/CategoryAPI.swift
  Projects/Core/Services/Category/CategoryService.swift
  Projects/Core/Services/HotKeyword/HotKeywordAPI.swift
  Projects/Core/Services/HotKeyword/HotKeywordService.swift
  Projects/Core/Services/MyPage/MyPageAPI.swift
  Projects/Core/Services/MyPage/MyPageService.swift
  Projects/Core/Services/NewsCard/NewsCardAPI.swift
  Projects/Core/Services/NewsCard/NewsCardService.swift
  Projects/Core/Services/_Foundation/ProviderError.swift
  Projects/DesignSystem/Sources/Views/ShortsWebView/ShortsWebView.swift
  Projects/DesignSystemWatchOS/Project.swift
  Projects/WatchApp/Info.plist
  Projects/WatchApp/Project.swift
  Projects/WatchApp/Sources/ContentView.swift
  Projects/WatchApp/Sources/SeeYouAgainWatchApp.swift
  Projects/WatchApp/xcconfigs/SeeYouAgain.debug.xcconfig
  Projects/WatchApp/xcconfigs/SeeYouAgain.release.xcconfig
  Projects/WatchApp/xcconfigs/SeeYouAgain.shared.xcconfig
  Tuist/Dependencies.swift
  Tuist/ProjectDescriptionHelpers/Target+extensions.swift
  Workspace.swift
Labels: 인프라, ⭐️⭐️⭐️ㅤ

#193 인프라: BundleIdentifier 변경
  Projects/Features/Scene/MyPageScene/MyPage/Achievements/MyAchievementsCore.swift
  Projects/Features/Scene/MyPageScene/MyPage/MyPageCore.swift
  Projects/WatchApp/Info.plist
  Projects/WatchApp/Project.swift
Labels: 인프라, ⭐️⭐️⭐️ㅤ

#195 애플 워치 타겟 추가
  Projects/App/Project.swift
  Projects/WatchApp/Project.swift
Labels: 인프라, ⭐️⭐️⭐️ㅤ
